name: passworthy
description: Simple yet secured password manager application built with Flutter.
homepage: https://github.com/thecodexhub/passworthy
version: 1.0.0+1

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.24.3

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  remote_flags_config:
    path: packages/remote_flags_config
  riverpod_annotation: ^2.6.1
  sentry_flutter: ^8.9.0

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.6.8
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true
  generate: true
