name: passworthy
description: Simple yet secured password manager application built with Flutter.
homepage: https://github.com/thecodexhub/passworthy
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.24.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
