name: remote_flags_config
description: Remote Config and Feature Flags config, using Flagsmith
  (https://www.flagsmith.com/).
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.24.3

dependencies:
  flagsmith: ^6.0.0
  flutter:
    sdk: flutter
  in_memory_cache:
    path: ../in_memory_cache

dev_dependencies:
  fake_async: ^1.3.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
